### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by runnamuck62** [lbrictson/pypubg#1]
I'm not able to import this module in Python 3. Is it compatible with Python 3?

**Comment by runnamuck62** [comment]
For more info, it is showing up in my python 3.5 site-packages, but I get the error 

```
Traceback (most recent call last):
  File "discordbot.py", line 15, in <module>
    from pypubg import core
ImportError: No module named 'pypubg
```

**Comment by lbrictson** [comment]
Hi @runnamuck62  sorry about that, were you using windows?

The issue should be fixed with version 0.0.3, apologies. (You'll want to pip uninstall pypubg and then reinstall it)

**Comment by runnamuck62** [comment]
Thanks! I was actually using Ubuntu 16.04

**Comment by MasterGroosha** [comment]
I have the same issue on Windows 10, module installed with pyCharm, python 3.5.2

Upd: same issue on Ubuntu 16.04, python 3.5. Cannot import module.

**Comment by lbrictson** [comment]
@MasterGroosha can you try installing the newest package? (v0.1.1)

You can either uninstall the current package or do an upgrade pip install --upgrade pypubg

Let me know if that works for you

**Comment by Benjamin-Connelly** [comment]
Same with OSX and Python 3.6:

`Successfully installed pypubg-0.1.1
⌂87% [MYUSERNAME:~] $
#python3.6
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypubg import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pypubg'`

**Comment by Benjamin-Connelly** [comment]
It may be OSX and path issues. I am setting up in my Debian dev environment. 

## Update
I tried this in debain with the same results:

>>> from pypubg import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pypubg'

**Comment by lbrictson** [comment]
I just pushed version 0.1.4, that should resolve the issue.  My apologies, I wasn't building the correct dist for all OS versions.

try:
`pip3 install --no-cache --upgrade pypubg`

and then try to run through the program

**Comment by Benjamin-Connelly** [comment]
That fixed it.

Thank you!

Benjamin


On July 17, 2017 at 4:48:20 PM, lbrictson (notifications@github.com) wrote:

I just pushed version 0.1.4, that should resolve the issue. My apologies, I
wasn't building the correct dist for all OS versions.

try:
pip3 install --no-cache --upgrade pypubg

and then try to run through the program

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lbrictson/pypubg/issues/1#issuecomment-315895135>, or mute
the thread
